# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Insiya' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Insiya

  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  pod 'react-native-amplitude-analytics', :path => '../node_modules/react-native-amplitude-analytics'

  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  # pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

  # pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

  target 'InsiyaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Insiya-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Insiya-tvOS

  target 'Insiya-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
